server:
  port: 8888

spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&serverTimezone=UTC
          password: root
        slave_1:
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          url: jdbc:mysql://localhost:3306/test-1?characterEncoding=utf-8&serverTimezone=UTC
          password: root
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&serverTimezone=UTC
#    password: root




logging:
  level:
    com.zjy.mapper: debug
